### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by kodekraft** [basho/riak-phppb-client#11]
In the`\Basho\Riak\Api\Pb::readMessageLength()`method, I occasionally have this exception raised:

`Exception 'ErrorException' with message 'unpack(): Type N: not enough input, need 4, have 0'`

A restart of the php-fpm service appears to alleviate the error.

**Comment by lukebakken** [comment]
@heylarson I re-opened to get some more information. Can you provide info as to what commands were executing at the time of the exception?

**Comment by kodekraft** [comment]
@lukebakken sorry, this issue was duplicated by another issue I created today #12 by accident, which is why I closed it. hopefully, the other issue contains more information for you.
