### ISSUE TITLE
Security tests are broken

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-phppb-client#17]
Reproduce:

```
git submodule update --init
./tools/setup-riak -s
make security-tests
```

`Makefile` and `phpunit.xml` both export `PB_INTERFACE = 1`, but it appears that TLS is not set up correctly. I don't see where the `RpbStartTls` message is sent, either.

**Comment by christophermancini** [comment]
Sweet, not sure how I missed that one... I will get this resolved quickly.
