### ISSUE TITLE
One of composer requirement is no available more (renamed, reversioned)

### ISSUE THREAD

**Issue by awesomeUA** [basho/riak-phppb-client#22]
"require": {
    "basho/riak": "^3.3",
    "php": ">=5.5",
    "ext-json": "*",
    "ext-curl": "*",
    "allegro/protobuf": "^1.0"
  },

allegro/protobuf does not exist any more
maybe its allegro/php-protobuf now

**Comment by kodekraft** [comment]
I think this needs to be reopened.  This dependency was never resolved.
